version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-backend
    environment:
      - DATABASE_URL=mysql://root:2222005@localhost:3306/mydb
    depends_on:
      - mysql
    volumes:
      - .:/app
    expose:
      - "3000"
    ports:
      - "3000:3000"  
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 2222005
      MYSQL_DATABASE: mydb
      # optional to set username and password
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 2222005
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - backend
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet; done'"
    restart: unless-stopped

volumes:
  db-data:
  
