# .github/workflows/deploy.yml
name: Deploy to VPS with Docker Compose

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy over SSH
        run: |
          ssh -o StrictHostKeyChecking=no user@your_server_ip
            cd /path/to/your/project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
