name: Cypress Tests

on:
  push:
    branches: [client]
  pull_request:
    branches: [client]

jobs:
  cypress-multi-browser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    strategy:
      matrix:
        browser: [chrome, firefox, edge]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests in ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./client 
          start: npm run dev
          wait-on: http://localhost:5173
          browser: ${{ matrix.browser }}
          command: npm run cy:run
